name: Server Rust Test

on: [push, pull_request]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./server

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup update

      - name: Format
        run: |
          cargo fmt -- --check

      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features

      - name: Build - Debug
        run: |
          cargo build

      - name: Build - Debug
        run: |
          cargo build --release

      - name: Test
        run: |
          cargo test
